-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "city" TEXT NOT NULL DEFAULT 'Gainesville, FL',
ADD COLUMN     "cityLat" DOUBLE PRECISION NOT NULL DEFAULT 29.6519563,
ADD COLUMN     "cityLng" DOUBLE PRECISION NOT NULL DEFAULT -82.324998;
