name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./deploy

      - name: Apply Terraform changes if needed
        run: terraform apply -auto-approve
        working-directory: ./deploy

      - name: Wait for infrastructure to complete
        run: |
          echo "Waiting for infrastructure to complete..."
          while [ "$(terraform output -raw rds-status)" != "available" ]; do
            echo "Infrastructure is not yet ready. Waiting for 10 seconds..."
            sleep 10
          done
          echo "Infrastructure is deployed!"
        working-directory: ./deploy

      - name: SSH into EC2 and pull Docker image from ECR
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > new-standard-key.pem
          chmod 600 new-standard-key.pem
          ssh -o StrictHostKeyChecking=no -i new-standard-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            # Login to ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 980921756008.dkr.ecr.us-east-1.amazonaws.com
            
            # Pull and run the Docker image
            docker pull 980921756008.dkr.ecr.us-east-1.amazonaws.com/roost-ecr-repo:latest
            docker run -d -p 3000:3000 980921756008.dkr.ecr.us-east-1.amazonaws.com/roost-ecr-repo:latest
          EOF