name: CI Pipeline

on:  
  workflow_run:
    workflows: ["Test Code"]
    types:
      - completed
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 980921756008.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t roost-ecr-repo .

      - name: Tag built image
        run: docker tag roost-ecr-repo:latest 980921756008.dkr.ecr.us-east-1.amazonaws.com/roost-ecr-repo:latest

      - name: Push image to repo
        run: docker push 980921756008.dkr.ecr.us-east-1.amazonaws.com/roost-ecr-repo:latest