name: Test Code

on:
  workflow_run:
    workflows: ["Lint Code"]
    types:
      - completed

jobs:
    test:
        runs-on: ubuntu-latest
        container: node:20
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with: 
                node-version: 20

            - name: Install packages
              run: npm ci

            - name: Run tests
              run: npm test
            